# Generated by Django 3.1.5 on 2021-01-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthez_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
