# Generated by Django 3.1.5 on 2021-01-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthez_app', '0002_listitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('img_url', models.TextField()),
            ],
        ),
    ]
