# Generated by Django 3.1.5 on 2021-01-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthez_app', '0003_searchitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='img_url',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='title',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
