# Generated by Django 3.1.5 on 2021-01-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthez_app', '0004_auto_20210116_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='food',
            name='title',
        ),
        migrations.AddField(
            model_name='food',
            name='data',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
