# Generated by Django 3.1.5 on 2021-01-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthez_app', '0005_auto_20210116_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='product_id',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchitem',
            name='product_id',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
