# Generated by Django 3.1.5 on 2021-01-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthez_app', '0006_auto_20210116_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='data',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listitem',
            name='img_url',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
