# Generated by Django 3.1.5 on 2021-01-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthez_app', '0007_auto_20210117_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_Image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
