# Generated by Django 3.1.5 on 2021-01-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthez_app', '0008_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='barcodeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.TextField()),
                ('data', models.JSONField()),
            ],
        ),
    ]
